### ISSUE TITLE
Add function to save/write a tree in Newick format

### ISSUE THREAD

**Issue by diegozea** [richardreeve/Phylo.jl#61]
I think it will be useful, particularly to share the tree between sessions and programs.

**Comment by richardreeve** [comment]
Yes, it's a good idea. I also want to write an entirely new parser for newick and nexus format, because the current one is a mess, and it looks like [CombinedParsers.jl](https://github.com/gkappler/CombinedParsers.jl) can handle recursion (finally, a julia parser that can!) - and something to convert between PhyloNetwork's format and this one, possibly just via a wrapper of some kind:

```julia
struct TreeWrapper{Tree} <: AbstractTree
  tree::Tree
end
```

where the wrapper implements our interface. From there I was wondering whether there was a sensible way of allowing us to traverse a tree to allow us to convert between any file format or tree format via a common interface... essentially iterating over the one you have while creating the other one. Just speculating really, but it would solve a lot of problems...

**Comment by richardreeve** [comment]
This was solved in #88.
